# Generated by Django 4.2.24 on 2026-01-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0002_mockuptemplate_generatedmockup'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockuptemplate',
            name='bound_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mockuptemplate',
            name='bound_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mockuptemplate',
            name='bound_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mockuptemplate',
            name='bound_y',
            field=models.IntegerField(default=0),
        ),
    ]
