# Generated by Django 5.2.9 on 2025-12-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='can_export_hd',
            new_name='allow_hd_export',
        ),
    ]
