# Generated by Django 5.2.9 on 2025-12-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_can_export_hd_subscriptionplan_allow_hd_export'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='can_remove_watermark',
            new_name='remove_watermark',
        ),
    ]
