# Generated by Django 5.2.9 on 2025-12-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_usermockupusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='can_use_premium_templates',
            new_name='allow_premium_templates',
        ),
    ]
